name: Build Mesa Amber Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mesa-amber:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar todas las dependencias de compilación para Mesa
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            meson ninja-build pkg-config bison flex \
            python3-mako python3-packaging \
            libz-dev libzstd-dev libexpat1-dev libelf-dev \
            libdrm-dev \
            libx11-dev libxext-dev libxdamage-dev libxshmfence-dev \
            libxxf86vm-dev libxrandr-dev x11proto-dev libx11-xcb-dev \
            libxcb-glx0-dev libxcb-dri2-0-dev libxcb-dri3-dev \
            libxcb-present-dev libxcb-shm0-dev libxcb-sync-dev \
            libxcb-xfixes0-dev libxcb-randr0-dev libxcb-keysyms1-dev \
            libwayland-dev wayland-protocols libwayland-egl-backend-dev \
            libglvnd-dev libglvnd-core-dev \
            libunwind-dev valgrind \
            llvm-dev libvulkan-dev glslang-tools spirv-tools \
            libsensors-dev

      - name: Clonar repositorio de Mesa (Rama Amber)
        run: git clone -b amber https://gitlab.freedesktop.org/mesa/mesa.git

      - name: Configurar el entorno con Meson
        run: |
          cd mesa
          # Configuramos la ruta de instalación a la carpeta 'mesa-dist'
          meson setup build -Damber=true --buildtype=release --prefix=$(pwd)/mesa-dist

      - name: Compilar e instalar el código
        run: |
          cd mesa
          ninja -C build
          # Extrae los binarios limpios a la carpeta 'mesa-dist'
          meson install -C build

      - name: Subir binarios compilados
        uses: actions/upload-artifact@v4
        with:
          name: mesa-amber-build
          # Subimos solo la carpeta con el resultado final
          path: mesa/mesa-dist/
