name: Build j-micx from Codeberg

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio desde Codeberg
      run: git clone https://codeberg.org/javiercplus/j-micx.git .

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libsdl2-dev \
          libsdl2-image-dev \
          pulseaudio-utils \
          libgl1-mesa-dev \
          libqrencode-dev \
          openjdk-17-jdk \
          openssl \
          libfuse2

    - name: Compilar binarios y servidor Java
      run: make 

    - name: Construir paquete AppImage
      run: make appimage

    - name: Subir artefacto AppImage
      uses: actions/upload-artifact@v4
      with:
        name: j-micx-appimage
        path: ./*.AppImage
